name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker-compose build
    - name: Spin up services
      run: docker-compose up -d
    - name: Wait 
      run: sleep 60
    - name: Check status
      run: docker ps -a
    - name: Test
      run: curl http://localhost:8080/ -L --fail -s | grep 'Sign in</button>' -q
    - name: Publish Docker Image to Docker Hub
      run: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        docker tag docker_humhub:latest humhub/humhub:latest
        docker push humhub/humhub:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
